name: Java CI Push

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '8'
      - name: Build with Maven
        env:
          AWS_REGION: us-east-1
          AWS_DEFAULT_REGION: us-east-1
        run: mvn clean package
